name: CD

on:
  workflow_dispatch:
    inputs:
      ZAHL1:
        description: 'Erste Zahl'
        required: true
        default: '8'
      ZAHL2:
        description: 'Zweite Zahl'
        required: true
        default: '4'
      OP:
        description: 'Operator (+, -, *, /)'
        required: true
        default: '*'

jobs:
  SetUp:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.latest_tag.outputs.tag }}
    steps:
      # Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get latest semver tag from DockerHub
      - name: Get latest semver tag from DockerHub
        id: latest_tag
        run: |
          TAGS=$(curl -s "https://registry.hub.docker.com/v2/repositories/jessimin/devops/tags?page_size=100" | jq -r '.results[].name')
          LATEST_TAG=$(echo "$TAGS" | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
          echo "No semver tags found on DockerHub for jessimin/devops."
          exit 1
          fi
          echo "Latest semver tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      # Check if latest Docker image exists
      - name: Check if latest Docker image exists
        run: |
          IMAGE="docker.io/jessimin/devops:${{ steps.latest_tag.outputs.tag }}"
          if docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
            echo "Image $IMAGE exists."
          else
            echo "Image $IMAGE does not exist."
            exit 1
          fi

  Deployment:
    needs: SetUp
    runs-on: ubuntu-latest
    steps:
      # Pull latest Docker image
      - name: Pull latest Docker image
        run: |
          docker pull jessimin/devops:${{ needs.SetUp.outputs.latest_tag }}
          
      # Deploy Application
      - name: Deploy Application
        run: |
          echo "Calculator Dummy starting..."
          docker run -d --name calculator \
            -e ZAHL1="${{ github.event.inputs.ZAHL1 }}" \
            -e ZAHL2="${{ github.event.inputs.ZAHL2 }}" \
            -e OP="${{ github.event.inputs.OP }}" \
            jessimin/devops:${{ needs.SetUp.outputs.latest_tag }}
          sleep 5
          echo "==== Application Output ===="
          docker logs calculator
          
      # Stop Calculator Container
      - name: Stop Calculator Container
        run: |
          docker stop calculator || true
          docker rm calculator || true
          docker rmi jessimin/devops:${{ needs.SetUp.outputs.latest_tag }} || true


  CleanUp:
    needs: [SetUp,Deployment]
    runs-on: ubuntu-latest
    steps:
      # Docker logout
      - name: Docker logout
        run: |
          echo "Logging out from Docker"
          docker logout