name: Java CI with Maven

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout codebase
      - uses: actions/checkout@v4

    # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
    # Building with Maven
      - name: Build with Maven
        working-directory: .
        run: mvn -B package

    # Lint Code Base
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Testing via JaCoCo/Surefire
      - name: Junit Test Dashboard
        uses: janisz/action@v2
        with:
          paths: target/surefire-reports/*.xml
          output: test-results.md
          show: all
